Repository KGU-Digital-Assistant/BE, pull requests merged in 2025-04, with the labels that each got.

#22 Feat: 트랙 시작하기 구현
  app/database_model.py
  app/migrations/versions/2025_03_25_1353-f3684bfdee51_add_track_participant.py
  app/migrations/versions/2025_03_25_1401-896e78a71cda_add_track_participant.py
  app/migrations/versions/2025_03_25_1514-21fbe4440b7d_add_track_participant_unique.py
  app/migrations/versions/2025_03_31_2049-0245c8f35e82_merge_routine_routinedate.py
  app/migrations/versions/2025_03_31_2140-18d5068076dd_del_column_routine_weekday.py
  app/migrations/versions/2025_03_31_2213-b6139af16920_change_mealtime_type.py
  app/migrations/versions/2025_04_01_0019-eb80287ee85d_add_col_image_url.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/domain/track.py
  app/modules/track/domain/track_participant.py
  app/modules/track/infra/db_models/track.py
  app/modules/track/infra/db_models/track_participant.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/__init__.py
  app/modules/track/interface/schema/track_schema.py
  app/modules/user/infra/db_models/user.py
  app/utils/exceptions/error_code.py
  app/utils/parser.py
  docker-compose.yml
  requirements.txt
Labels: ✨ Feature, 🔨 Refactor

#23 Feat: MealDay 구현(타 db연동, Dish, Meal 구현, Mealhour 삭제)#15
  app/config.py
  app/containers.py
  app/core/fcm.py
  app/main.py
  app/migrations/versions/2025_04_02_1157-cdf83c5514e3_revision_mealday.py
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/mealday.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/db_models/mealday.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/mealday/interface/schema/mealday_schema.py
  app/modules/user/domain/repository/user_repo.py
  app/modules/user/domain/user.py
  app/modules/user/infra/db_models/user.py
  app/modules/user/infra/user_repo_impl.py
  app/utils/exceptions/error_code.py
Labels: ✨ Feature, 🔨 Refactor

#27 Refactor: Food 모듈 분리 (#26)
  app/containers.py
  app/database_model.py
  app/main.py
  app/modules/food/__init__.py
  app/modules/food/application/__init__.py
  app/modules/food/application/food_service.py
  app/modules/food/domain/__init__.py
  app/modules/food/domain/food.py
  app/modules/food/domain/repository/__init__.py
  app/modules/food/domain/repository/food_repo.py
  app/modules/food/infra/__init__.py
  app/modules/food/infra/db_models/__init__.py
  app/modules/food/infra/db_models/food.py
  app/modules/food/infra/food_repo_impl.py
  app/modules/food/interface/__init__.py
  app/modules/food/interface/controller/__init__.py
  app/modules/food/interface/controller/v1/__init__.py
  app/modules/food/interface/controller/v1/food_controller.py
  app/modules/food/interface/schema/__init__.py
  app/modules/food/interface/schema/food_schema.py
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/mealday.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/db_models/mealday.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/mealday/interface/schema/mealday_schema.py
  app/utils/exceptions/error_code.py
Labels: 🔨 Refactor

#28 Feat: 트랙 복제 구현
  app/app_config.py
  app/core/auth.py
  app/core/fcm.py
  app/database.py
  app/main.py
  app/migrations/versions/2025_04_02_1157-cdf83c5514e3_revision_mealday.py
  app/modules/mealday/application/mealday_service.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/track_schema.py
  app/tests/conftest.py
  app/tests/test_settings.py
  app/tests/track/__init__.py
  app/tests/track/test_track.py
  app/utils/phone_verify.py
  requirements.txt
Labels: ✨ Feature, 🔨 Refactor

#33 Refactor: Meal, Dish 반정규화
  app/containers.py
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/mealday.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/db_models/mealday.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/infra/repository/track_repo_impl.py
Labels: 🔨 Refactor

#34 Feat: RoutineFood 구현
  app/containers.py
  app/database_model.py
  app/main.py
  app/migrations/versions/2025_04_13_1456-5398f4c41d48_connect_routine_food.py
  app/migrations/versions/2025_04_13_1521-25a44c24c652_add_quantity_and_casecade.py
  app/migrations/versions/2025_04_13_1537-74c90b953283_add_routine_food.py
  app/migrations/versions/2025_04_13_1541-e087e7e59628_fix_routinefood_int_str.py
  app/migrations/versions/2025_04_13_1720-dbc17e082d04_add_routinefood_id.py
  app/migrations/versions/2025_04_13_1847-834dc86c4ece_add_routinefood_unique.py
  app/modules/food/application/food_service.py
  app/modules/food/domain/food.py
  app/modules/food/domain/repository/food_repo.py
  app/modules/food/infra/db_models/food.py
  app/modules/food/infra/food_repo_impl.py
  app/modules/food/interface/controller/v1/food_controller.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/domain/track.py
  app/modules/track/domain/track_routine_food.py
  app/modules/track/infra/db_models/track.py
  app/modules/track/infra/db_models/track_participant.py
  app/modules/track/infra/db_models/track_routine_food.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/track_schema.py
  app/utils/exceptions/error_code.py
Labels: ✨ Feature

#35 Feat: Check 통계 테이블 생성
  app/containers.py
  app/migrations/versions/2025_04_15_0018-e56a098514b1_del_meal_and_change_col.py
  app/migrations/versions/2025_04_15_0053-137d9bbf938d_add_routine_food_check.py
  app/modules/food/application/food_service.py
  app/modules/food/interface/controller/v1/food_controller.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/track_routine_food.py
  app/modules/track/infra/db_models/track.py
  app/modules/track/infra/db_models/track_participant.py
  app/modules/track/infra/db_models/track_routine_food.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/track_schema.py
Labels: ✨ Feature, 🔨 Refactor

#36 Feat: RoutineCheck 적용된 GET 구현 (#30)
  app/migrations/versions/2025_04_15_2354-293eedf9bec7_add_routine_check.py
  app/migrations/versions/2025_04_16_0211-5bdd883ba802_add_routine_check_food_user_id.py
  app/modules/mealday/application/mealday_service.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/domain/track.py
  app/modules/track/domain/track_routine_food.py
  app/modules/track/infra/db_models/track.py
  app/modules/track/infra/db_models/track_routine_food.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/track_schema.py
  app/utils/exceptions/error_code.py
Labels: ✨ Feature

#40 Feat: Track 일차별 실제 날짜 출력
  app/main.py
  app/migrations/versions/2025_04_13_1847-834dc86c4ece_add_routinefood_unique.py
  app/migrations/versions/2025_04_16_1714-731484971472_add_food_col_image_url.py
  app/modules/food/domain/food.py
  app/modules/food/infra/db_models/food.py
  app/modules/food/interface/schema/food_schema.py
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/domain/track_participant.py
  app/modules/track/domain/track_routine_food.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/track_schema.py
  app/utils/exceptions/error_code.py
  app/utils/scheduler.py
Labels: ✨ Feature, 🔨 Refactor

#42 Refact : Dish 수량 Column 추가 및 Picture Column명 변경 #41
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/mealday.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/db_models/mealday.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/schema/mealday_schema.py
Labels: 🔨 Refactor

#44 Refact: 도커세팅으로 인한 경로 수정
  .gitignore
  Dockerfile
  app/containers.py
  app/core/auth.py
  app/core/fcm.py
  app/database.py
  app/database_model.py
  app/main.py
  app/modules/food/application/food_service.py
  app/modules/food/domain/food.py
  app/modules/food/domain/repository/food_repo.py
  app/modules/food/infra/db_models/food.py
  app/modules/food/infra/food_repo_impl.py
  app/modules/food/interface/controller/v1/food_controller.py
  app/modules/food/interface/schema/food_schema.py
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/mealday.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/db_models/mealday.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/mealday/interface/schema/mealday_schema.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/domain/track.py
  app/modules/track/domain/track_participant.py
  app/modules/track/infra/db_models/track.py
  app/modules/track/infra/db_models/track_participant.py
  app/modules/track/infra/db_models/track_routine_food.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/modules/track/interface/controller/v1/track_controller.py
  app/modules/track/interface/schema/track_schema.py
  app/modules/user/application/user_service.py
  app/modules/user/domain/repository/user_repo.py
  app/modules/user/domain/user.py
  app/modules/user/infra/db_models/user.py
  app/modules/user/infra/user_repo_impl.py
  app/modules/user/interface/controller/v1/user_controller.py
  app/modules/user/interface/schema/user_schema.py
  app/utils/exceptions/handlers.py
  app/utils/parser.py
  app/utils/phone_verify.py
  app/utils/scheduler.py
  requirements.txt
Labels: ⚙ Setting, 🔨 Refactor

#47 Feat: Dish update, remove 구현 및 계획없는 식단 출력 API 구현
  app/modules/mealday/application/mealday_service.py
  app/modules/mealday/domain/repository/mealday_repo.py
  app/modules/mealday/infra/mealday_repo_impl.py
  app/modules/mealday/interface/controller/v1/mealday_controller.py
  app/modules/mealday/interface/schema/mealday_schema.py
  app/modules/track/application/track_service.py
  app/modules/track/domain/repository/track_repo.py
  app/modules/track/infra/repository/track_repo_impl.py
  app/utils/exceptions/error_code.py
Labels: ✨ Feature

#46 Test: user 테스트 코트 작성
  .gitignore
  app/app_config.py
  app/migrations/versions/2025_04_13_1720-dbc17e082d04_add_routinefood_id.py
  app/modules/user/infra/user_repo_impl.py
  app/modules/user/interface/controller/v1/user_controller.py
  app/modules/user/interface/schema/user_schema.py
  app/tests/conftest.py
  app/tests/test_users/__init__.py
  app/tests/test_users/test_user.py
  app/tests/track/test_track.py
  app/tests/utils.py
  migrations/README
  migrations/__init__.py
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/2025_01_13_1703-eb712c3b6bc3_add_user.py
  migrations/versions/2025_01_13_1744-34c36e203dc9_add_user.py
  migrations/versions/2025_01_15_0455-c6d410aaf79a_change_user.py
  migrations/versions/2025_01_15_0505-610d5b57aa9d_gender_rank_user.py
  migrations/versions/2025_01_17_0327-48cd5c5c4056_add_username_unique.py
  migrations/versions/2025_01_26_2236-638489b9293c_fcm_birth_nullabel.py
  migrations/versions/2025_02_02_0038-af221a33be71_add_track.py
  migrations/versions/2025_02_02_0510-2c56ec5a6899_fix_rout_date_id.py
  migrations/versions/2025_02_27_2037-be67c74b7fb2_add_mealday.py
  migrations/versions/2025_03_25_1353-f3684bfdee51_add_track_participant.py
  migrations/versions/2025_03_25_1401-896e78a71cda_add_track_participant.py
  migrations/versions/2025_03_25_1514-21fbe4440b7d_add_track_participant_unique.py
  migrations/versions/2025_03_31_2049-0245c8f35e82_merge_routine_routinedate.py
  migrations/versions/2025_03_31_2140-18d5068076dd_del_column_routine_weekday.py
  migrations/versions/2025_03_31_2213-b6139af16920_change_mealtime_type.py
  migrations/versions/2025_04_01_0019-eb80287ee85d_add_col_image_url.py
  migrations/versions/2025_04_02_1157-cdf83c5514e3_revision_mealday.py
  migrations/versions/2025_04_13_1456-5398f4c41d48_connect_routine_food.py
  migrations/versions/2025_04_13_1521-25a44c24c652_add_quantity_and_casecade.py
  migrations/versions/2025_04_13_1537-74c90b953283_add_routine_food.py
  migrations/versions/2025_04_13_1541-e087e7e59628_fix_routinefood_int_str.py
  migrations/versions/2025_04_13_1720-dbc17e082d04_add_routinefood_id.py
  migrations/versions/2025_04_15_0018-e56a098514b1_del_meal_and_change_col.py
  migrations/versions/2025_04_15_0053-137d9bbf938d_add_routine_food_check.py
  migrations/versions/2025_04_15_2354-293eedf9bec7_add_routine_check.py
  migrations/versions/2025_04_16_0211-5bdd883ba802_add_routine_check_food_user_id.py
  migrations/versions/2025_04_16_1714-731484971472_add_food_col_image_url.py
  migrations/versions/__init__.py
Labels: ✅ Test
